/**
 * Quote Manager
 *
 * Loads quotes from data/quotes.json (generated by the analysis script).
 * Falls back to placeholder quotes for development.
 * Handles mood filtering, rotation, and transitions.
 */

import quotesJson from '../data/quotes.json'

export interface Quote {
  text: string
  mood: string
  date: string
  era: string
  context: string
  from_type: string
  theme?: string
  themes?: string[]
  tags?: string[]
}

export interface Theme {
  name: string
  description: string
  color_hint?: string
  quote_count?: number
}

export interface QuoteData {
  meta: { total_emails_scanned: number; total_quotes: number }
  themes: Theme[]
  timeline_narrative: string
  quotes: Quote[]
}

const data = quotesJson as QuoteData
export const THEMES: Theme[] = data.themes ?? []
export const TIMELINE_NARRATIVE: string = data.timeline_narrative ?? ''

export const MOODS = [
  'all', 'funny', 'sad', 'outrageous', 'profound',
  'mundane', 'tender', 'angry', 'absurd', 'nostalgic', 'existential',
] as const

export type Mood = typeof MOODS[number]

// Mood → color mapping for rendering
export const MOOD_COLORS: Record<string, { hue: number; sat: number; light: number }> = {
  funny:       { hue: 45,  sat: 90, light: 65 },
  sad:         { hue: 220, sat: 50, light: 55 },
  outrageous:  { hue: 350, sat: 85, light: 60 },
  profound:    { hue: 270, sat: 45, light: 60 },
  mundane:     { hue: 180, sat: 15, light: 55 },
  tender:      { hue: 330, sat: 45, light: 65 },
  angry:       { hue: 5,   sat: 75, light: 55 },
  absurd:      { hue: 160, sat: 65, light: 55 },
  nostalgic:   { hue: 35,  sat: 35, light: 55 },
  existential: { hue: 250, sat: 25, light: 55 },
}

/**
 * Placeholder quotes for development.
 * Replace with real data from data/quotes.json after running the analysis.
 */
const PLACEHOLDER_QUOTES: Quote[] = [
  // --- First email ---
  {
    text: "Lost Tools of Learning by Dorothy Sayers.",
    mood: "profound",
    date: "2004-08-19",
    era: "2004-2006",
    context: "The very first email — from a high school speech & debate teacher, 4 years after graduation",
    from_type: "teacher",
  },
  // --- Funny ---
  {
    text: "I accidentally replied all to 200 people saying 'love you bye' instead of just my mom",
    mood: "funny",
    date: "2009-03-14",
    era: "2007-2009",
    context: "Accidental reply-all at work",
    from_type: "self",
  },
  {
    text: "The printer is on fire again. Not metaphorically. Call facilities.",
    mood: "funny",
    date: "2011-07-22",
    era: "2010-2012",
    context: "Office emergency email chain",
    from_type: "coworker",
  },
  {
    text: "Who keeps stealing my yogurt? This is the third time this week. I will find you.",
    mood: "funny",
    date: "2014-02-11",
    era: "2013-2015",
    context: "Break room drama",
    from_type: "coworker",
  },
  // --- Sad ---
  {
    text: "I wish I had more time to tell you how much you meant to all of us",
    mood: "sad",
    date: "2012-11-05",
    era: "2010-2012",
    context: "Loss of a colleague",
    from_type: "friend",
  },
  {
    text: "The house is empty now. Even the echoes feel different.",
    mood: "sad",
    date: "2017-08-30",
    era: "2016-2018",
    context: "After a major life transition",
    from_type: "family",
  },
  // --- Outrageous ---
  {
    text: "Per my last email, which you clearly did not read, the deadline was YESTERDAY",
    mood: "outrageous",
    date: "2015-06-18",
    era: "2013-2015",
    context: "Passive-aggressive project management",
    from_type: "coworker",
  },
  {
    text: "They want us to work the weekend AND bring our own lunch? What is this, a pyramid scheme?",
    mood: "outrageous",
    date: "2018-09-07",
    era: "2016-2018",
    context: "Company all-hands meeting aftermath",
    from_type: "coworker",
  },
  // --- Profound ---
  {
    text: "Every city you've ever lived in still holds a version of you walking its streets",
    mood: "profound",
    date: "2020-04-15",
    era: "2019-2021",
    context: "Pandemic reflection with an old friend",
    from_type: "friend",
  },
  {
    text: "The best decisions I ever made looked like mistakes for the first two years",
    mood: "profound",
    date: "2016-01-03",
    era: "2016-2018",
    context: "Career advice from a mentor",
    from_type: "coworker",
  },
  // --- Mundane ---
  {
    text: "Can you pick up milk on the way home? The 2% kind, not whole.",
    mood: "mundane",
    date: "2013-04-22",
    era: "2013-2015",
    context: "Grocery run coordination",
    from_type: "family",
  },
  {
    text: "Running 5 minutes late. Save me a seat near the outlet.",
    mood: "mundane",
    date: "2019-11-14",
    era: "2019-2021",
    context: "Coffee shop meetup",
    from_type: "friend",
  },
  // --- Tender ---
  {
    text: "I still have every letter you wrote me. They're in the blue box in my closet.",
    mood: "tender",
    date: "2008-12-25",
    era: "2007-2009",
    context: "Holiday email exchange",
    from_type: "family",
  },
  {
    text: "You don't have to be strong right now. Just be here.",
    mood: "tender",
    date: "2021-03-08",
    era: "2019-2021",
    context: "Supporting a friend through difficulty",
    from_type: "friend",
  },
  // --- Absurd ---
  {
    text: "Why is there a goat in the parking lot? This is a tech company.",
    mood: "absurd",
    date: "2016-10-31",
    era: "2016-2018",
    context: "Halloween at the office",
    from_type: "coworker",
  },
  {
    text: "I just got an email from my dentist wishing me happy birthday. We are not friends.",
    mood: "absurd",
    date: "2022-06-15",
    era: "2022-2024",
    context: "Automated birthday email existential crisis",
    from_type: "self",
  },
  // --- Nostalgic ---
  {
    text: "Remember when we used to build forts out of couch cushions and call it architecture?",
    mood: "nostalgic",
    date: "2010-08-12",
    era: "2010-2012",
    context: "Reconnecting with a childhood friend",
    from_type: "friend",
  },
  {
    text: "Found a photo of us from 2006. We looked so young. We were so young.",
    mood: "nostalgic",
    date: "2023-01-20",
    era: "2022-2024",
    context: "Photo cleanup session",
    from_type: "friend",
  },
  // --- Existential ---
  {
    text: "Do you ever wonder if we're just performing ourselves in every email we send?",
    mood: "existential",
    date: "2019-07-04",
    era: "2019-2021",
    context: "Late night philosophical exchange",
    from_type: "friend",
  },
  {
    text: "333,000 emails and I'm not sure a single one of them captured what I actually meant to say",
    mood: "existential",
    date: "2026-04-28",
    era: "2025-now",
    context: "Reflecting on this very project",
    from_type: "self",
  },
  // --- Angry ---
  {
    text: "I have been transferred to six different departments and no one can help me cancel this subscription",
    mood: "angry",
    date: "2017-03-19",
    era: "2016-2018",
    context: "Customer service hell",
    from_type: "self",
  },
]


export const ALL_THEMES = 'all'

export class QuoteManager {
  quotes: Quote[] = []
  currentMood: Mood = 'all'
  currentTheme: string = ALL_THEMES
  currentTag: string | null = null
  currentIndex: number = 0
  private filtered: Quote[] = []

  constructor() {
    const bundled = data.quotes
    this.quotes = bundled && bundled.length > 0 ? bundled : PLACEHOLDER_QUOTES
    this.rebuildFiltered()
  }

  private shuffle() {
    for (let i = this.filtered.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1))
      ;[this.filtered[i], this.filtered[j]] = [this.filtered[j], this.filtered[i]]
    }
  }

  private rebuildFiltered() {
    let f = this.quotes
    if (this.currentMood !== 'all') f = f.filter(q => q.mood === this.currentMood)
    if (this.currentTheme !== ALL_THEMES) f = f.filter(q => q.theme === this.currentTheme)
    if (this.currentTag) {
      const tag = this.currentTag
      f = f.filter(q => Array.isArray(q.tags) && q.tags.includes(tag))
    }
    this.filtered = [...f]
    this.shuffle()
    this.currentIndex = 0
  }

  filterByMood(mood: Mood) {
    this.currentMood = mood
    this.rebuildFiltered()
  }

  filterByTheme(theme: string) {
    if (theme === this.currentTheme) return
    this.currentTheme = theme
    // Tag is theme-scoped; clear it when the theme changes
    this.currentTag = null
    this.rebuildFiltered()
  }

  /** Toggle a tag on/off. Pass null to clear. */
  filterByTag(tag: string | null) {
    this.currentTag = tag
    this.rebuildFiltered()
  }

  /** Tags + counts limited to the currently selected theme. */
  tagsInCurrentTheme(): Array<{ tag: string; count: number }> {
    const counts = new Map<string, number>()
    for (const q of this.quotes) {
      if (this.currentTheme !== ALL_THEMES && q.theme !== this.currentTheme) continue
      if (!Array.isArray(q.tags)) continue
      for (const t of q.tags) counts.set(t, (counts.get(t) ?? 0) + 1)
    }
    return [...counts.entries()]
      .map(([tag, count]) => ({ tag, count }))
      .sort((a, b) => b.count - a.count)
  }

  nextMood(direction: 1 | -1 = 1) {
    const idx = MOODS.indexOf(this.currentMood)
    const nextIdx = (idx + direction + MOODS.length) % MOODS.length
    this.filterByMood(MOODS[nextIdx])
  }

  current(): Quote | null {
    if (this.filtered.length === 0) return null
    return this.filtered[this.currentIndex % this.filtered.length]
  }

  next(): Quote | null {
    if (this.filtered.length === 0) return null
    this.currentIndex = (this.currentIndex + 1) % this.filtered.length
    return this.current()
  }

  get moodLabel(): string {
    return this.currentMood === 'all' ? 'all moods' : this.currentMood
  }

  get themeLabel(): string {
    return this.currentTheme === ALL_THEMES ? 'all themes' : this.currentTheme
  }

  get count(): number {
    return this.filtered.length
  }

  /**
   * Chronologically-sorted snapshot of every quote in the dataset.
   * Filters do NOT apply — time-lapse mode iterates the full archive.
   * ISO YYYY-MM-DD dates sort correctly lexicographically.
   */
  chronological(): Quote[] {
    return [...this.quotes].sort((a, b) => (a.date ?? '').localeCompare(b.date ?? ''))
  }
}

/**
 * Find the most recent quote whose date is <= targetIso (e.g. '2018-08-23').
 * Quotes must be pre-sorted by date ascending. Returns the last quote when
 * targetIso is past every entry, the first when it predates them all.
 */
export function quoteAtDate(sortedQuotes: Quote[], targetIso: string): Quote | null {
  if (sortedQuotes.length === 0) return null
  if (targetIso < sortedQuotes[0].date) return sortedQuotes[0]
  // Binary search for last index with date <= targetIso
  let lo = 0
  let hi = sortedQuotes.length - 1
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1
    if (sortedQuotes[mid].date <= targetIso) lo = mid
    else hi = mid - 1
  }
  return sortedQuotes[lo]
}
